### PR TITLE
Display an error message when the API doesn't respond

### LINKED ISSUE #136: Frozen page on api internal server error
When I search for `https://legislation.openfisca.fr/paje_cmg`, the page stays on `Chargement des valeurs…`.

We could give more information to the user as on this peculiar context, an API call to this variable `https://fr.openfisca.org/api/v20/variable/paje_cmg` gives: 
```
{
  "error": "Internal server error: 'ascii' codec can't decode byte 0xc3 in position 112: ordinal not in range(128)"
}
```

### PR DESCRIPTION
**Pull request by fpagnoux**
Fixes #136 

Before:
image

After:

image

### CODE REVIEW

File: src/server/webpack-dev-server.js [hunk 1]
```diff
@@ -15,6 +15,9 @@ new WebpackDevServer(webpack(webpackDevConfig), {
   publicPath: webpackDevConfig.output.publicPath,
   stats: { colors: true },
   quiet: true,
+  headers: {
+    'Access-Control-Allow-Origin': '*',
```
Comment (fpagnoux) [inline src/server/webpack-dev-server.js]: > Avoid CORS error when using an `.env` file locally

File: webpack.config.dev.js [hunk 2]
```diff
@@ -21,6 +21,7 @@ module.exports = {
   devtool: 'source-map', // Original code
   entry: {
     'main': [
+      'babel-polyfill',
```
Comment (fpagnoux) [inline webpack.config.dev.js]: > To be able to use `async/await`

File: src/webservices.js [hunk 3]
```diff
@@ -3,23 +3,17 @@ import fetch from 'isomorphic-fetch'
...
-          }
-        }
-        if (data.error) {
-          throw new Error(JSON.stringify(data.error))
-        }
-        throw new Error(JSON.stringify({error: 'Unexpected return code ' + response.status}))
-      })
-  )
+async function fetchJson(url, options) {
+  const response = await fetch(url, options)
```
[the remark this answers is not in the document]
Comment (fpagnoux) [reply src/webservices.js]: Added it 🙂
